twitter/config/routes.rb
Rails.application.routes.draw do
    root 'users#index'
    resources :users do
        resources :tweets
        resources :follows
    end
    get 'connect/:id', to: 'users#connect', as: 'connect'
    get 'disconnect', to: 'users#disconnect', as: 'disconnect'
    get 'follow/:followed', to: 'follows#create', as: 'follow'
    get 'unfollow/:followed', to: 'follows#destroy', as: 'unfollow'
    get 'fil-actualite', to: 'tweets#filActu', as: 'filActu'
    get 'tendances', to: 'tweets#tendances', as: 'tendances'
    get 'tendances/:hashtag', to: 'tweets#tendances', as: 'hashtag'

end

twitter/app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
end

twitter/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :content, :presence => true
end

twitter/app/models/user.rb
class User < ActiveRecord::Base
    has_many :tweets
    has_many :follows

    validates :name, :presence => true
    validates :first_name, :presence => true
end

twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

twitter/app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    def create
        @follower = User.find(session[:current_user]['id'])
        @followed = User.find(params[:followed])
        @follow = @follower.follows.create({:user => @follower, :followed => params[:followed]})
        redirect_to user_path(@followed)
    end

    def destroy
        @user = User.find(session[:current_user]['id'])
        @followed = User.find(params[:followed])
        @follow = Follow.find_by user: @user, followed: params[:followed]
        @delete = @user.follows.find(@follow['id'])
        @delete.destroy
        redirect_to user_path(@followed)
    end
end

twitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def create
        @user = User.find(params[:user_id])
        @tweet = @user.tweets.create(tweet_params)
        redirect_to user_path(@user)
    end

    def filActu
        if session[:current_user]
            @tweets = []
            @usersID = []
            @user = User.find(session[:current_user]['id'])
            @user.follows.each do |follow|
                @usersID << follow.followed
            end
            @usersID << session[:current_user]['id']
            Tweet.all.each do |tweet|
                if @usersID.include? tweet.user_id
                    @tweets << {:user => User.find(tweet.user_id), :tweet => tweet}
                end
            end
            @tweets = @tweets.sort {|x, y| y[:tweet].created_at <=> x[:tweet].created_at}

        end
    end

    def tendances
        if session[:current_user]
            @tweets = []
            @all_hashtags = []
            @hashtags = []
            @nb_hashtags = []
            @selected = params[:hashtag]
            Tweet.all.each do |tweet|
                tag = tweet.content[/#[[:alnum:]]*/]
                if tag != nil
                    @all_hashtags << tag
                    if !@hashtags.include? tag
                        @hashtags << tag
                    end
                end
                @tweets << {:user => User.find(tweet.user_id), :tweet => tweet}
            end
            @tweets = @tweets.sort {|x, y| y[:tweet].created_at <=> x[:tweet].created_at}

            @hashtags.each do |tag|
                @nb_hashtags << {:tag => tag, :count => @all_hashtags.count(tag)}
            end
            @nb_hashtags.sort! {|x, y| y[:count] <=> x[:count]}
        end
    end

    private
        def tweet_params
            params.require(:tweet).permit(:content)
        end
end

twitter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    if session[:current_user]
      @me = User.find(session[:current_user]['id'])
      @is_followed = Follow.find_by user: @me, followed: @user.id
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    Tweet.all.each do |tweet|
        if tweet.user_id == @user.id
            tweet.destroy
        end
    end
    @user.follows.each do |follow|
        follow.destroy
    end
    Follow.all.each do |follow|
        if follow.followed == @user.id
            follow.destroy
        end
    end
    if @user.id == session[:current_user]['id']
        session.delete(:current_user)
    end
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  def connect
    @user = User.find(params[:id])
    session[:current_user] = @user
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Connexion réussie !' }
    end
  end

  def disconnect
    session.delete(:current_user)
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Déconnexion réussie !' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :first_name, :img_url)
    end
end

twitter/app/helpers/application_helper.rb
module ApplicationHelper
end

twitter/app/helpers/tweets_helper.rb
module TweetsHelper
end

twitter/app/helpers/users_helper.rb
module UsersHelper
end

twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>RubyTwitter</title>
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav>
            <div class="nav-wrapper grey darken-4">
                <ul class="left hide-on-med-and-down">
                    <li><a href="<%= users_path %>">Liste des utilisateurs</a></li>
                    <% if session[:current_user] %>
                        <li><a href="<%= filActu_path %>">Mon fil d'actualité</a></li>
                        <li><a href="<%= tendances_path %>">Tendances</a></li>
                    <% end %>
                </ul>
                <a href="<%= root_path %>" class="brand-logo center"><img src="<%= image_path('logo.png') %>" width="30" height="30" class="d-inline-block align-top" alt=""> Twitter On Rails</a>
                <ul class="right hide-on-med-and-down">
                    <% if session[:current_user] %>
                        <li><a href="<%= user_path(session[:current_user]['id']) %>">Connecté en tant que : <%= session[:current_user]['first_name'] %> <%= session[:current_user]['name'] %></a></li>
                        <li><a href="<%= disconnect_path %>">Déconnexion</a></li>
                    <% end %>
                </ul>
            </div>
        </nav>
        <%= yield %>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>
</html>

twitter/app/views/tweets/filActu.html.erb
<h1 class="title">Mon fil d'actualité</h1>
<div class="container">
    <div class="row">
        <div class="col s12 green-text">
            <%= notice %>
        </div>
        <div class="col s12 valign-wrapper">
            <i class="small material-icons">info</i> <p style="margin-left: 5px;">Suivez d'autres personnes pour afficher plus de tweets</p>
        </div>
        <%
            @tweets.each do |tweet|
                %>
                <div class="col s12 tweet <%= if tweet[:user].id == session[:current_user]['id'] then 'me' end %>">
                    <a class="aImage" href="<%= user_path(tweet[:user].id) %>"><div class="image" style="background-image: url(<%= image_path(tweet[:user].img_url) %>)"></div></a>
                    <div class="content">
                        <div class="info"><%= tweet[:user].first_name %> <%= tweet[:user].name %> a tweeté le <i><%= tweet[:tweet].created_at.strftime('%a %d %b %Y à %Hh%M') %></i> : </div>
                        <div class="text"><%= tweet[:tweet].content %></div>
                    </div>
                </div>
                <%
            end

            if @tweets.length == 0
                %>
                <div class="col s12 center-align">
                    Aucun tweet à afficher
                </div>
                <%
            end
        %>
    </div>
</div>

twitter/app/views/tweets/tendances.html.erb
<h1 class="title">Tendances actuelles</h1>
<div class="container">
    <div class="row">
        <div class="col s12 green-text">
            <%= notice %>
        </div>
        <div class="col s8">
            <h2><%= if @selected then '#'+@selected else 'Derniers tweets' end %></h2>
            <%
                @tweets.each do |tweet|
                    if @selected != "" && tweet[:tweet].content[/##{@selected}*/]
                    %>
                    <div class="col s12 tweet <%= if tweet[:user].id == session[:current_user]['id'] then 'me' end %>">
                        <a class="aImage" href="<%= user_path(tweet[:user].id) %>"><div class="image" style="background-image: url(<%= image_path(tweet[:user].img_url) %>)"></div></a>
                        <div class="content">
                            <div class="info"><%= tweet[:user].first_name %> <%= tweet[:user].name %> a tweeté le <i><%= tweet[:tweet].created_at.strftime('%a %d %b %Y à %Hh%M') %></i> : </div>
                            <div class="text"><%= tweet[:tweet].content %></div>
                        </div>
                    </div>
                    <%
                    end
                end
            %>
        </div>
        <div class="col s4">
            <h2>Top Tweets</h2>
            <ul class="collection">
            <% @nb_hashtags.each do |hashtag| %>
                <li class="collection-item">
                    <a href="<%= hashtag_path(hashtag[:tag].delete '#') %>"><%= hashtag[:tag] %></a><span class="badge"><%= hashtag[:count] %></span>
                </li>
            <% end %>
            </ul>
        </div>
    </div>
</div>

twitter/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

twitter/app/views/users/edit.html.erb
<h1 class="title">Modifier mes informations</h1>
<div class="container">
    <div class="row">
        <div class="col s12">
            <%= render 'form' %>
        </div>
        <div class="col s12">
            <%= link_to 'Show', @user %> |
            <%= link_to 'Back', users_path %>
        </div>
    </div>
</div>

twitter/app/views/users/index.html.erb
<h1 class="title">Liste des utilisateurs</h1>
<div class="container">
    <div class="row">
        <div class="col s12 green-text center-align">
            <%= notice %>
        </div>
        <div class="col s12 center-align">
            <% @users.each do |user| %>
                <a href="<%= user_path(user) %>">
                    <div class="user" style="background-image: url(<%= image_path(user.img_url) %>)">
                        <div class="dark">
                            <div class="name"><%= user.first_name %> <%= user.name %></div>
                        </div>
                    </div>
                </a>
            <% end %>
            <a href="<%= new_user_path %>">
                <div class="user new">
                    <i class="material-icons">add</i>
                </div>
            </a>
        </div>
    </div>
</div>

twitter/app/views/users/new.html.erb
<p id="notice"><%= notice %></p>
<h1 class="title">Ajouter un utilisateur</h1>
<div class="container">
    <div class="row">
        <div class="col s12">
            <%= render 'form' %>
        </div>
        <div class="col s12">
            <%= link_to 'Back', users_path %>
        </div>
    </div>
</div>

twitter/app/views/users/show.html.erb
<h1 class="title"><%= @user.first_name %> <%= @user.name %></h1>
<div class="container">
    <div class="row">
        <div class="col s12 green-text">
            <%= notice %>
        </div>
        <div class="col s12">
            <img src="<%= image_path(@user.img_url) %>" class="pdp" />
        </div>
        <% if session[:current_user] && session[:current_user]['id'] == @user.id %>
            <div class="col s12">
                <h2>Tweets de <%= @user.first_name %></h2>
                <ul class="collection">
                <% @user.tweets.each do |tweet| %>
                  <li class="collection-item"><i><%= tweet.created_at.strftime('%a %d %b %Y à %Hh%M') %></i> : <%= tweet.content %></li>
                <% end %>
                <% if @user.tweets.length == 0 %>
                  <li class="collection-item">Vous n'avez pas encore tweeté</li>
                <% end %>
                </ul>
            </div>
            <div class="col s12">
                <h2>Abonnements :</h2>
                <ul class="collection">
                <% @user.follows.each do |follow| %>
                  <% @followed = User.find(follow.followed) %>
                  <li class="collection-item">
                      <%= @followed.first_name %> <%= @followed.name %>
                      <span class="badge"><a href="<%= unfollow_path(@followed.id) %>">Ne plus suivre cet utilisateur</a></span>
                  </li>
                <% end %>
                <% if @user.follows.length == 0 %>
                  <li class="collection-item">Aucun abonnement</li>
                <% end %>
                </ul>
            </div>
            <div class="col s12">
                <h2>Add a tweet:</h2>
                <%= form_for([@user, @user.tweets.build]) do |f| %>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">textsms</i>
                        <%= f.text_field :content %>
                    </div>
                    <%= f.submit %>
                </div>
                <% end %>
            </div>
            <div class="col s12">
                <%= link_to 'Supprimer', user_path(@user), method: :delete %> |
                <%= link_to 'Modifier', edit_user_path(@user) %> |
                <%= link_to 'Retour', users_path %> |
                <%= link_to 'Se déconnecter', disconnect_path %>
            </div>
        <% elsif @is_followed %>
            <div class="col s12">
                <h2>Tweets de <%= @user.first_name %></h2>
                <ul class="collection">
                <% @user.tweets.each do |tweet| %>
                  <li class="collection-item"><i><%= tweet.created_at.strftime('%a %d %b %Y à %Hh%M') %></i> : <%= tweet.content %></li>
                <% end %>
                <% if @user.tweets.length == 0 %>
                  <li class="collection-item"><%= @user.first_name %> <%= @user.name %> n'a pas encore tweeté</li>
                <% end %>
                </ul>
            </div>
            <div class="col s12">
                <%= link_to 'Retour', users_path %> |
                <%= link_to 'Utiliser ce compte', connect_path(@user.id) %> |
                <a href="<%= unfollow_path(@user.id) %>">Ne plus suivre cet utilisateur</a>
            </div>
        <% elsif session[:current_user] %>
            <div class="col s12 valign-wrapper">
                <i class="small material-icons">info</i> <p style="margin-left: 5px;">Suivez cette personne pour voir ses tweets</p>
            </div>
            <div class="col s12">
                <%= link_to 'Back', users_path %> |
                <%= link_to 'Utiliser ce compte', connect_path(@user.id) %> |
                <a href="<%= follow_path(@user.id) %>">Suivre cet utilisateur</a>
            </div>
        <% else %>
            <div class="col s12 valign-wrapper">
                <i class="small material-icons">info</i> <p style="margin-left: 5px;">Connectez-vous à ce compte pour éditer le profil</p>
            </div>
            <div class="col s12">
                <%= link_to 'Back', users_path %> |
                <%= link_to 'Utiliser ce compte', connect_path(@user.id) %>
            </div>
        <% end %>
    </div>
</div>